### ISSUE TITLE
Matriz de Comunicação

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.1-RPGym#14]
- [x] Onde estão os produtos gerados na Sprint 0: Documentação da Sprint Planning, Tasks no kanban, relatório diário, Documentação da Sprint Review, Documentação da Sprint, Relatório de Situação do Projeto
- [x] O líder estelar deve ser inserido na matriz de comunicação

**Comment by AkaeRanni** [comment]
Feito!
