### ISSUE TITLE
Objetivos do produto

### ISSUE THREAD

**Issue by juliaryoshida** [mdsreq-fga-unb/2024.1-RPGym#37]
- [x] Explicar de forma geral como vocês pretendem atingir os objetivos secundários com a aplicação. Por exemplo, no tópico "Educar os usuários sobre os benefícios da atividade física para a saúde física e mental", como isso será implementado na aplicação?
- [x] Associar os objetivos secundários aos requisitos. Ex.: a US07 "Eu, como usuário, gostaria de criar um grupo e convidar meus amigos para incentivar uns aos outros a praticar exercícios físicos" é importante porque ela ajuda a atingir o objetivo "Estabelecer uma comunidade colaborativa onde os usuários possam se apoiar mutuamente."

**Comment by AkaeRanni** [comment]
Feituu
