### ISSUE TITLE
Backlog da sprint

### ISSUE THREAD

**Issue by juliaryoshida** [mdsreq-fga-unb/2024.1-RPGym#38]
Definir em qual sprint e como cada disciplina da engenharia de requisitos foi usada.

**Comment by Akaeboshi** [comment]
Feito!

**Comment by AkaeRanni** [comment]
Fechei sem querer kk

**Comment by daramariabs** [comment]
Atividades de engenharia de requisitos adicionada ao backlog da sprint, consultar documentação para verificar correção.
