### ISSUE TITLE
Processo de desenvolvimento de software

### ISSUE THREAD

**Issue by juliaryoshida** [mdsreq-fga-unb/2024.1-RPGym#40]
- [x] Foi definido que o grupo utilizaria apenas 3 das cerimônias do SCRUM, mas SCRUM sem todas as cerimônias não é SCRUM
- [x] Não foi definido o tempo de cada sprint e no cronograma algumas sprints tem duração diferentes
- [x] Definir o que é cada uma das atividades da Engenharia de Requisitos

**Comment by AkaeRanni** [comment]
Feito
