### ISSUE TITLE
Backlog do produto

### ISSUE THREAD

**Issue by juliaryoshida** [mdsreq-fga-unb/2024.1-RPGym#42]
- [x] Descrever mais detalhadamente os critérios de aceitação, definindo formatos, limites de cada entrada, tipo de dado aceito, quantidade de caracteres aceitos, etc. 
- [x] Em todas as histórias de usuário colocar "para...", pra mostrar o porquê ela é necessária.
- [x] Explicar como foi feita a divisão de US por MVP. Em quais critérios o grupo se baseou pra dividir dessa forma? Naquela tabela de desenvolvimento de produto, vocês colocaram os níveis de prioridades, mas como eles foram definidos? Seria interessante pensar em critérios como complexidade técnica e valor de negócio.
- [x] Colocar a que tipo cada requisito não funcional se refere(usabilidade, confiabilidade, etc).
- [x] Colocar na tabela de US os objetivos aos quais cada uma das US se relaciona.
- [x] Seria melhor fazer uma única tabela pros artefatos do backlog safe ao invés de dividir em várias, pois facilita visualizar e relacionar os épicos X capacidades X funcionalidades X user stories.

**Comment by AkaeRanni** [comment]
Não entendi muito bem o que seriam esses Objetivos. Se puder explicar melhor, por favor.
