### ISSUE TITLE
USM

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.1-RPGym#44]
- A estrutura está correta.

- O conteúdo, está incorreto, em um nível de granularidade muito baixo. E, quando chega nas US, está em um nível de campo. Cada US a inserção de um campo. Não faz sentido. Todo o mapa precisa de revisão. O problema está no nível de granularidade das atividades. a partir delas, deve-se ajustar as US.
- Exemplos:
- 
![image](https://github.com/user-attachments/assets/64eaa2d3-8d8b-4e83-ab98-06b56d330718)
![image](https://github.com/user-attachments/assets/1d1e43c8-ab49-4f26-93be-99cb13176630)

**Comment by daramariabs** [comment]
As correções solicitadas estão disponíveis na missão 3.
